spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-craigmiller160.ddns.net/realms/apps-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: market-tracker-portfolio-service
      principal-attribute: preferred_username

