spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-craigmiller160.ddns.net/realms/apps-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  db:
    baseUrl: postgresql://localhost:5432/market_tracker_portfolio_dev
    username: postgres
    password: password
  r2dbc:
    url: r2dbc:${spring.db.baseUrl}
    username: ${spring.db.username}
    password: ${spring.db.password}
  flyway:
    url: jdbc:${spring.db.baseUrl}
    user: ${spring.db.username}
    password: ${spring.db.password}


jwt:
  auth:
    converter:
      resource-id: market-tracker-portfolio-service
      principal-attribute: preferred_username

downloaders:
  interval-cron: 0 0 */3 * * *
  craigmiller:
    service-account-json: ${user.dir}/market-tracker-service-account.json