server:
  port: 8082

spring:
  security:
    keycloak:
      oauth2:
        resourceserver:
          host: https://auth.craigmiller160.us
          realm: apps-dev
          client-id: market-tracker-portfolio-service
  db:
    baseUrl: postgresql://localhost:5432/market_tracker_portfolio_dev
    username: postgres
    password: password
  r2dbc:
    url: r2dbc:${spring.db.baseUrl}
    username: ${spring.db.username}
    password: ${spring.db.password}
  flyway:
    url: jdbc:${spring.db.baseUrl}
    user: ${spring.db.username}
    password: ${spring.db.password}

http-client:
  timeout-millis: 30000

downloaders:
  enable-schedule: false
  interval-rate-hours: 3
  craigmiller:
    user-id: 2e0eccce-1f64-4d13-a269-fda027f5ddee
    google-sheets-api-base-url: https://sheets.googleapis.com/v4
    service-account-json-path: ${user.dir}/market-tracker-service-account.json
    portfolio-spreadsheets-standard:
      - name: Brokerage
        sheet-id: 1E2U1DR7i3xG3Kvi_AH9Zp_uYRYR2sSobcjQ5Di1a_t0
        values-range: Transactions
      - name: Roth IRA
        sheet-id: 18BK_urWmKH_m9bZFVOpDzRDgqQ66gTwdnYil-xtKZK4
        values-range: Transactions
    portfolio-spreadsheets-401k:
      - name: 401k
        sheet-id: 14ICDVPp6LPhoUDEgsA5ZP7bopr7GTzdFf1jbcxEhouE
        values-range: 401k
        allocations:
          - start-date: 2015-01-01
            end-date: 2022-11-30
            percent-us: 100%
            percent-ex-us: 0%
          - start-date: 2022-12-01
            percent-us: 80%
            percent-ex-us: 20%
#      - name: Rollover IRA
#        sheet-id: 1Kuj9Ky_DYh0IsUgXx48rMKgRD7oU7O5xqwylNwx1VN0
#        values-range: Transactions

logging:
  level:
    io.craigmiller160: DEBUG
    org.springframework.data.r2dbc: DEBUG
#    io.r2dbc.postgresql.QUERY: DEBUG