spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-craigmiller160.ddns.net/realms/apps-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/market_tracker_portfolio_dev
    username: postgres
    password: password

jwt:
  auth:
    converter:
      resource-id: market-tracker-portfolio-service
      principal-attribute: preferred_username